### ISSUE TITLE
Assistant substitute?

### ISSUE THREAD

**Issue by rootsmusic** [GiraffeReversed/thonny-edulint#4]
Is this plug-in intending to be an alternative (or that will be comparable) to Assistant?  Edulint replaces Assistant's mypy with flake8.  (The previous sentence is just a comparative diff, because I don't know what it means.)

P.S. the [library's docs](https://edulint.readthedocs.io/en/latest/#overview) are too technical for Thonny users.  Can we have a dummy-version [Wiki](https://github.com/GiraffeReversed/thonny-edulint/wiki/)?

**Comment by GiraffeReversed** [comment]
Hi :)

Thonny Assistant provides several kinds of assistance, mostly aimed at helping with debugging: it helps with understanding Python error messages and it reports possible sorts of bugs (like undefined variables or possible type errors) using Pylint and mypy.

thonny-edulint starts running EduLint: a tool which is more focused on improving coding style and code quality.

thonny-edulint turns off the Pylint checks in Assistants, as it itself runs Pylint in the background (no reason to run it twice), but leaves the rest of the Assistant as it is (so it still helps in decrypting Python error message and hints at some sources of bugs).

So, EduLint does not replace mypy (any mypy checks in Thonny should be left as they are, and if they are not, then it is a bug I am not aware of). EduLint uses flake8, Pylint and a number of custom detectors.

EduLint's documentation is aimed primarily at educators, while thonny-edulint is aimed at students. There are brief instructions how to install and use the plugin in Thonny in the [README.md](https://github.com/GiraffeReversed/thonny-edulint#readme). However, I will consider restructuring EduLint's documentation to provide a better landing page with a disambiguation for different kinds of users.  

Does this help/answer your questions? :)

**Comment by rootsmusic** [comment]
Yes @GiraffeReversed, I can understand the difference between Assistant and Edulint now.  However, I'm unable to distinguish between categories like: linter, formatter, parser, and type checker (in Python, "type" refers to types for .astype).  Thanks for creating a plugin to help users like me!

In my search to understand flake8, I found [flake9](https://pypi.org/project/flake9/).  So I assume that Edulint will plan to update its flake version.

P.S. Thonny's Assistant has wanted to improve its pylint implementation, but it's [an old issue](https://github.com/thonny/thonny/issues/1037).

**Comment by GiraffeReversed** [comment]
Regarding flake8, it is not a new version of flake8 (the 8 in the name probably refers to PEP8 it helps to enforce, rather than a version). The pip page even states: "Flake9 is a fork of Flake8 that supports reading configuration from a pyproject.toml file, because the authors of Flake8 won’t implement it.", meaning flake9 just adds a feature that flake8 does not have. I do not plan to transition to it, as the feature would not be useful to an educational tool.

As for the categories you mention: I believe it is not the purpose of GitHub issues to explain this kind of stuff, but I am an educator at heart so here goes some short explanation:
linter = a tool for providing feedback on code (can regard formatting, bugs, vulnerabilities etc.)
formatter = a tool that formats code (typically adds/removes spaces and newlines and such)
parser = a tool that turns raw text into another representation for further processing (see for example abstract syntax tree)
type checker = a tool that checks type safety of code (looks for type errors like adding a string to a number and such)

However, I do plan to substitute flake8 and possibly pylint with [ruff](https://github.com/astral-sh/ruff), which reimplements most of the detectors in Rust and is faster by several orders of magnitude.

I really cannot guess what Thonny contributors meant by the issue you refer to. There is no description and that issue has been inactive for several years. I believe the code quality feedback EduLint provides is more useful to novice programmers than the feedback currently provided by Pylint through Thonny Assistant.

**Comment by rootsmusic** [comment]
Thanks @GiraffeReversed, Thonny will also consider changing Assistant to ruff in the future.  In the mean time, I've installed your plugin in the latest version of Thonny.  Since Thonny opens a Edulint pane, I think that your plugin is working.
